---
language: node_js
node_js:
- '0.8'
- '0.10'
before_script:
- npm install -g grunt-cli
- nohup phantomjs --webdriver=4444 > /dev/null &
- sleep 3
env:
  global:
  - secure: ! 'FS5tU4qtln1lrTv3PqWrQxVs3MAoJf7sbba2dISXLs7AR5IbluD2dkvrKG0H

      EziB1Uk37QU/AJXvWnE26z07aQn32r71N1YVUWDpdb9EW7s4aQAYXF9+JLG3

      AToVU/EG21qXbRjxbKXEoF1AeADmHsErsgk2h3TNUyNh9+ubQeQ='
  - secure: ! 'mrabOe/9B1ec8cq/iOd9jFlAtO2yRQOZlKyFMjNzqwiC7XFjLTiI/D3eV8/h

      gTH8kN/EKZ5s+DKSZkwDK1BTrWJ9B3MGbPvOhjCeWaY0hpYWPGuolReu5311

      XYON4DAqOmzV1wHPHI/EZVULH7wHBBOflyVTHbr1JB2QY2bVsjI='
